import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the plugin's GitHub repository:
https://github.com/swayinfo/eltonlabs-book-reader
*/
`;

const prod = process.argv[2] === "production";

const ctx = await esbuild.context({
  entryPoints: ["src/main.js"],
  bundle: true,
  // Obsidian supplies these at runtime; bundling them would break the plugin.
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  // No source map in the release build: it tripled the file size, and reviewers
  // read the sources in src/ anyway.
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  banner: { js: banner },
  minify: false,
});

if (prod) {
  await ctx.rebuild();
  // pdf.js runs its heavy parsing in a worker. Shipping the worker next to the
  // plugin keeps PDFs working offline; without it the reader falls back to a CDN.
  const worker = path.join("node_modules", "pdfjs-dist", "build", "pdf.worker.js");
  if (fs.existsSync(worker)) {
    fs.copyFileSync(worker, "pdf.worker.js");
    console.log("pdf.worker.js copied from pdfjs-dist");
  } else {
    console.warn("pdf.worker.js not found in node_modules — PDFs will load the worker from a CDN");
  }
  process.exit(0);
} else {
  await ctx.watch();
}
