import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";

// Заглушка глобального Iterator. pdf.js 6 в первой же строке проверяет
// `typeof Iterator.prototype.join`, считая, что глобальный Iterator существует.
// Он появился только в Chrome 122 (февраль 2024): на Obsidian 1.5–1.6 (движок 114),
// на iOS постарше и на планшетах Huawei с их собственным движком строка падает
// с «ReferenceError: Iterator is not defined» ещё до запуска плагина — и Obsidian
// показывает «Не удалось загрузить плагин». Пять строк ниже возвращают этим
// устройствам работающую читалку; на свежих движках блок не делает ничего.
const iteratorShim = `(function(){try{if(typeof globalThis.Iterator==="function")return;
var proto=Object.getPrototypeOf(Object.getPrototypeOf([][Symbol.iterator]()));
var Iter=function Iterator(){throw new TypeError("Iterator is abstract")};
Iter.prototype=proto;
try{Object.defineProperty(proto,"constructor",{value:Iter,writable:true,configurable:true})}catch(e){}
globalThis.Iterator=Iter}catch(e){}})();
`;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the plugin's GitHub repository:
https://github.com/swayinfo/elton-reader
*/
${iteratorShim}`;

const prod = process.argv[2] === "production";

// Embed the pdf.js worker straight into the bundle instead of shipping it as a
// separate pdf.worker.js file. Two reasons: (1) PDFs then work fully offline with
// no CDN fallback, and (2) BRAT only ever downloads main.js / manifest.json /
// styles.css from a release, so a separate worker file would simply never reach
// BRAT users. At runtime setupWorker() turns this string into a Blob URL.
function loadPatchedWorker() {
  // pdf.js 4+ поставляет воркер как ES-модуль (.mjs). Берём legacy-сборку: она
  // рассчитана на движки постарше, а Obsidian на телефоне бывает именно таким.
  const candidates = [
    path.join("node_modules", "pdfjs-dist", "legacy", "build", "pdf.worker.mjs"),
    path.join("node_modules", "pdfjs-dist", "build", "pdf.worker.mjs"),
    path.join("node_modules", "pdfjs-dist", "build", "pdf.worker.js"),
    path.join("node_modules", "pdfjs-dist", "legacy", "build", "pdf.worker.js"),
  ];
  const wp = candidates.find((p) => fs.existsSync(p));
  if (!wp) {
    throw new Error("pdf.worker.js not found in node_modules — run `npm install` first");
  }
  let code = fs.readFileSync(wp, "utf8");
  // Same sentence-period fix as patch-pdfjs.cjs, applied in memory so the embedded
  // worker is always patched regardless of whether patch-pdfjs.cjs ran. Idempotent.
const OLD = "/^(\\s)|(\\p{Mn})|(\\p{Cf})$/u";   // в файле: /^(\s)|(\p{Mn})|(\p{Cf})$/u
  const NEW = "/^(\\s+)$|(\\p{Mn})|(\\p{Cf})$/u"; // в файле: /^(\s+)$|(\p{Mn})|(\p{Cf})$/u
  if (!code.includes(NEW) && code.includes(OLD)) {
    code = code.split(OLD).join(NEW);
    console.log("pdf.worker: sentence-period patch applied (in memory)");
  }
  code = code.replace(/\nexport \{[^}]*\};\s*$/, "\n");
  // Воркер живёт в своём глобальном контексте — заглушка нужна и ему.
  return iteratorShim + code;
}
const workerCode = loadPatchedWorker();

// Внутри pdf.js, epub.js и jszip есть ветки, которые создают <script> и
// подгружают код по ссылке. В Obsidian они не выполняются никогда: воркер pdf.js
// вшит в сборку, страницы EPUB мы разбираем сами и ничего не рендерим в iframe,
// а «script-таймер» в jszip — полифил для IE, который в Chrome не выбирается.
// Автопроверка каталога, однако, читает текст сборки и справедливо считает такие
// места загрузкой произвольного кода. Поэтому мёртвые ветки вырезаются на сборке
// — целенаправленно и по одному месту, чтобы правка оставалась проверяемой:
// каталог пересобирает плагин из исходников и сверяет результат побайтово.
const neutralise = {
  name: "neutralise-dead-script-injection",
  setup(build) {
    const targets = /node_modules[\\/](pdfjs-dist|jszip|epubjs)[\\/].*\.(js|mjs)$/;
    build.onLoad({ filter: targets }, async (args) => {
      let code = await fs.promises.readFile(args.path, "utf8");
      // ветка-полифил в jszip: заставляем выбрать MessageChannel
      code = code.split('"onreadystatechange" in global.document.createElement("script")').join("false");
      code = code.split('"onreadystatechange" in doc.createElement("script")').join("false");
      code = code.split('"onreadystatechange" in global.document.createElement("script")').join("false");
      // загрузка внешнего скрипта: у нас её не бывает
      code = code.split('document.createElement("script")').join('document.createElement("template")');
      code = code.split("document.createElement('script')").join("document.createElement('template')");
      code = code.split('doc.createElement("script")').join('doc.createElement("template")');
      code = code.split("doc.createElement('script')").join("doc.createElement('template')");
      return { contents: code, loader: "js" };
    });
  },
};

const ctx = await esbuild.context({
  entryPoints: ["src/main.js"],
  bundle: true,
  // Obsidian supplies these at runtime; bundling them would break the plugin.
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    // Узловые модули перечислены явно: пакет builtin-modules каталог просит не
    // использовать, а список нам нужен ровно затем, чтобы esbuild не пытался
    // затащить серверные ветки библиотек в браузерную сборку.
    "assert", "buffer", "child_process", "crypto", "events", "fs", "http",
    "https", "net", "os", "path", "process", "querystring", "stream", "string_decoder",
    "tls", "url", "util", "worker_threads", "zlib",
  ],
  // Узловые модули и необязательное хранилище epub.js подменяются пустышкой.
  // Иначе в сборку попадает серверный код pdf.js (`require("fs")`) и ветки
  // localforage, которые в Obsidian никогда не выполняются, зато выглядят для
  // автопроверки каталога как доступ к файловой системе и загрузка скриптов.
  alias: {
    fs: "./build-stubs/empty.js",
    http: "./build-stubs/empty.js",
    https: "./build-stubs/empty.js",
    url: "./build-stubs/empty.js",
    zlib: "./build-stubs/empty.js",
    stream: "./build-stubs/empty.js",
    canvas: "./build-stubs/empty.js",
    localforage: "./build-stubs/empty.js",
  },
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  // No source map in the release build: it tripled the file size, and reviewers
  // read the sources in src/ anyway.
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  banner: { js: banner },
  plugins: [neutralise],
  minify: false,
  // Injected as a plain string literal; setupWorker() reads it as __PDF_WORKER_CODE__.
  define: { __PDF_WORKER_CODE__: JSON.stringify(workerCode) },
});

if (prod) {
  await ctx.rebuild();
  // The pdf.js worker is now embedded in main.js (see loadPatchedWorker above), so
  // there is no separate pdf.worker.js to copy or ship.
  console.log("build complete — pdf.worker embedded into main.js");
  process.exit(0);
} else {
  await ctx.watch();
}
