import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the plugin's GitHub repository:
https://github.com/swayinfo/eltonlabs-book-reader
*/
`;

const prod = process.argv[2] === "production";

// Embed the pdf.js worker straight into the bundle instead of shipping it as a
// separate pdf.worker.js file. Two reasons: (1) PDFs then work fully offline with
// no CDN fallback, and (2) BRAT only ever downloads main.js / manifest.json /
// styles.css from a release, so a separate worker file would simply never reach
// BRAT users. At runtime setupWorker() turns this string into a Blob URL.
function loadPatchedWorker() {
  const candidates = [
    path.join("node_modules", "pdfjs-dist", "build", "pdf.worker.js"),
    path.join("node_modules", "pdfjs-dist", "legacy", "build", "pdf.worker.js"),
  ];
  const wp = candidates.find((p) => fs.existsSync(p));
  if (!wp) {
    throw new Error("pdf.worker.js not found in node_modules — run `npm install` first");
  }
  let code = fs.readFileSync(wp, "utf8");
  // Same sentence-period fix as patch-pdfjs.cjs, applied in memory so the embedded
  // worker is always patched regardless of whether patch-pdfjs.cjs ran. Idempotent.
  const OLD = '"^(\\\\s)|(\\\\p{Mn})|(\\\\p{Cf})$"';   // literal in file: "^(\\s)|(\\p{Mn})|(\\p{Cf})$"
  const NEW = '"^(\\\\s+)$|(\\\\p{Mn})|(\\\\p{Cf})$"'; // literal in file: "^(\\s+)$|(\\p{Mn})|(\\p{Cf})$"
  if (!code.includes(NEW) && code.includes(OLD)) {
    code = code.split(OLD).join(NEW);
    console.log("pdf.worker: sentence-period patch applied (in memory)");
  }
  return code;
}
const workerCode = loadPatchedWorker();

const ctx = await esbuild.context({
  entryPoints: ["src/main.js"],
  bundle: true,
  // Obsidian supplies these at runtime; bundling them would break the plugin.
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  // No source map in the release build: it tripled the file size, and reviewers
  // read the sources in src/ anyway.
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  banner: { js: banner },
  minify: false,
  // Injected as a plain string literal; setupWorker() reads it as __PDF_WORKER_CODE__.
  define: { __PDF_WORKER_CODE__: JSON.stringify(workerCode) },
});

if (prod) {
  await ctx.rebuild();
  // The pdf.js worker is now embedded in main.js (see loadPatchedWorker above), so
  // there is no separate pdf.worker.js to copy or ship.
  console.log("build complete — pdf.worker embedded into main.js");
  process.exit(0);
} else {
  await ctx.watch();
}
